import json

# Comprehensive mapping of city to (country, flag)
CITY_COUNTRY_FLAG = {
    # Major cities
    "Moscow": ("Russia", "🇷🇺"),
    "Saint Petersburg": ("Russia", "🇷🇺"),
    "London": ("UK", "🇬🇧"),
    "New York": ("USA", "🇺🇸"),
    "Paris": ("France", "🇫🇷"),
    "Berlin": ("Germany", "🇩🇪"),
    "Tokyo": ("Japan", "🇯🇵"),
    "Beijing": ("China", "🇨🇳"),
    "Rome": ("Italy", "🇮🇹"),
    "Madrid": ("Spain", "🇪🇸"),
    "Lisbon": ("Portugal", "🇵🇹"),
    "Istanbul": ("Turkey", "🇹🇷"),
    "Bangkok": ("Thailand", "🇹🇭"),
    "Dubai": ("UAE", "🇦🇪"),
    "Dublin": ("Ireland", "🇮🇪"),
    "Budapest": ("Hungary", "🇭🇺"),
    "Vienna": ("Austria", "🇦🇹"),
    "Prague": ("Czech Republic", "🇨🇿"),
    "Warsaw": ("Poland", "🇵🇱"),
    "Zurich": ("Switzerland", "🇨🇭"),
    
    # Russian cities
    "Abakan": ("Russia", "🇷🇺"),
    "Arkhangelsk": ("Russia", "🇷🇺"),
    "Astrakhan": ("Russia", "🇷🇺"),
    "Barnaul": ("Russia", "🇷🇺"),
    "Belgorod": ("Russia", "🇷🇺"),
    "Bryansk": ("Russia", "🇷🇺"),
    "Cheboksary": ("Russia", "🇷🇺"),
    "Chelyabinsk": ("Russia", "🇷🇺"),
    "Chernyahovsk": ("Russia", "🇷🇺"),
    "Derbent": ("Russia", "🇷🇺"),
    "Elista": ("Russia", "🇷🇺"),
    "Irkutsk": ("Russia", "🇷🇺"),
    "Ivanovo": ("Russia", "🇷🇺"),
    "Kaliningrad": ("Russia", "🇷🇺"),
    "Kaluga": ("Russia", "🇷🇺"),
    "Kazan": ("Russia", "🇷🇺"),
    "Kemerovo": ("Russia", "🇷🇺"),
    "Khabarovsk": ("Russia", "🇷🇺"),
    "Khuzhir": ("Russia", "🇷🇺"),
    "Kirov": ("Russia", "🇷🇺"),
    "Kislovodsk": ("Russia", "🇷🇺"),
    "Kostroma": ("Russia", "🇷🇺"),
    "Krasnodar": ("Russia", "🇷🇺"),
    "Krasnoyarsk": ("Russia", "🇷🇺"),
    "Kursk": ("Russia", "🇷🇺"),
    "Kyzyl": ("Russia", "🇷🇺"),
    "Magnitogorsk": ("Russia", "🇷🇺"),
    "Makhachkala": ("Russia", "🇷🇺"),
    "Maykop": ("Russia", "🇷🇺"),
    "Murmansk": ("Russia", "🇷🇺"),
    "Nab. Chelny": ("Russia", "🇷🇺"),
    "Nalchik": ("Russia", "🇷🇺"),
    "Novorossiysk": ("Russia", "🇷🇺"),
    "Novosibirsk": ("Russia", "🇷🇺"),
    "Omsk": ("Russia", "🇷🇺"),
    "Orenburg": ("Russia", "🇷🇺"),
    "Oryol": ("Russia", "🇷🇺"),
    "Perm": ("Russia", "🇷🇺"),
    "Petropavlovsk-Kamchatskiy": ("Russia", "🇷🇺"),
    "Petrozavodsk": ("Russia", "🇷🇺"),
    "Pskov": ("Russia", "🇷🇺"),
    "Pyatigorsk": ("Russia", "🇷🇺"),
    "Rostov-on-Don": ("Russia", "🇷🇺"),
    "Ryazan": ("Russia", "🇷🇺"),
    "Rybinsk": ("Russia", "🇷🇺"),
    "Samara": ("Russia", "🇷🇺"),
    "Saratov": ("Russia", "🇷🇺"),
    "Smolensk": ("Russia", "🇷🇺"),
    "Sochi": ("Russia", "🇷🇺"),
    "Stavropol": ("Russia", "🇷🇺"),
    "Surgut": ("Russia", "🇷🇺"),
    "Tambov": ("Russia", "🇷🇺"),
    "Tolyatti": ("Russia", "🇷🇺"),
    "Tomsk": ("Russia", "🇷🇺"),
    "Tula": ("Russia", "🇷🇺"),
    "Tutaev": ("Russia", "🇷🇺"),
    "Tver": ("Russia", "🇷🇺"),
    "Tyumen": ("Russia", "🇷🇺"),
    "Ufa": ("Russia", "🇷🇺"),
    "Uglich": ("Russia", "🇷🇺"),
    "Ulan-Ude": ("Russia", "🇷🇺"),
    "Ulyanovsk": ("Russia", "🇷🇺"),
    "Velikiy Novgorod": ("Russia", "🇷🇺"),
    "Vladikavkaz": ("Russia", "🇷🇺"),
    "Vladimir": ("Russia", "🇷🇺"),
    "Vladivostok": ("Russia", "🇷🇺"),
    "Volgograd": ("Russia", "🇷🇺"),
    "Voronezh": ("Russia", "🇷🇺"),
    "Vyborg": ("Russia", "🇷🇺"),
    "Yakutsk": ("Russia", "🇷🇺"),
    "Yaroslavl": ("Russia", "🇷🇺"),
    "Yekaterinburg": ("Russia", "🇷🇺"),
    "Yuzhno-Sakhalinsk": ("Russia", "🇷🇺"),
    
    # Other cities
    "Abu Dhabi": ("UAE", "🇦🇪"),
    "Agra": ("India", "🇮🇳"),
    "Alanya": ("Turkey", "🇹🇷"),
    "Amsterdam": ("Netherlands", "🇳🇱"),
    "Antalya": ("Turkey", "🇹🇷"),
    "Athens": ("Greece", "🇬🇷"),
    "Baku": ("Azerbaijan", "🇦🇿"),
    "Barcelona": ("Spain", "🇪🇸"),
    "Batumi": ("Georgia", "🇬🇪"),
    "Bogota": ("Colombia", "🇨🇴"),
    "Bordeaux": ("France", "🇫🇷"),
    "Brest (Belarus)": ("Belarus", "🇧🇾"),
    "Brno": ("Czech Republic", "🇨🇿"),
    "Brussels": ("Belgium", "🇧🇪"),
    "Busan": ("South Korea", "🇰🇷"),
    "Cancun": ("Mexico", "🇲🇽"),
    "Chennai": ("India", "🇮🇳"),
    "Chiang Mai": ("Thailand", "🇹🇭"),
    "Chicago": ("USA", "🇺🇸"),
    "Da Nang": ("Vietnam", "🇻🇳"),
    "Dammam": ("Saudi Arabia", "🇸🇦"),
    "Delhi": ("India", "🇮🇳"),
    "Denpasar": ("Indonesia", "🇮🇩"),
    "Fethiye": ("Turkey", "🇹🇷"),
    "Florence": ("Italy", "🇮🇹"),
    "Frankfurt": ("Germany", "🇩🇪"),
    "Fukuoka": ("Japan", "🇯🇵"),
    "Gelendzhik": ("Russia", "🇷🇺"),
    "Gomel": ("Belarus", "🇧🇾"),
    "Goreme, Cappadocia": ("Turkey", "🇹🇷"),
    "Gorno-Altaysk": ("Russia", "🇷🇺"),
    "Grodno": ("Belarus", "🇧🇾"),
    "Grozny": ("Russia", "🇷🇺"),
    "Guangzhou": ("China", "🇨🇳"),
    "Ha Long": ("Vietnam", "🇻🇳"),
    "Hamburg": ("Germany", "🇩🇪"),
    "Hanoi": ("Vietnam", "🇻🇳"),
    "Helsinki": ("Finland", "🇫🇮"),
    "Heraklion": ("Greece", "🇬🇷"),
    "Ho Chi Minh City": ("Vietnam", "🇻🇳"),
    "Hong Kong": ("China", "🇨🇳"),
    "Jaipur": ("India", "🇮🇳"),
    "Jakarta": ("Indonesia", "🇮🇩"),
    "Jeju": ("South Korea", "🇰🇷"),
    "Jerusalem": ("Israel", "🇮🇱"),
    "Johannesburg": ("South Africa", "🇿🇦"),
    "Johor Bahru": ("Malaysia", "🇲🇾"),
    "Kas, Turkiye": ("Turkey", "🇹🇷"),
    "Krabi": ("Thailand", "🇹🇭"),
    "Kuala Lumpur": ("Malaysia", "🇲🇾"),
    "Kutaisi": ("Georgia", "🇬🇪"),
    "Kyoto": ("Japan", "🇯🇵"),
    "Las Vegas": ("USA", "🇺🇸"),
    "Lima": ("Peru", "🇵🇪"),
    "Los Angeles": ("USA", "🇺🇸"),
    "Macau": ("China", "🇨🇳"),
    "Mecca": ("Saudi Arabia", "🇸🇦"),
    "Medina": ("Saudi Arabia", "🇸🇦"),
    "Mexico City": ("Mexico", "🇲🇽"),
    "Miami": ("USA", "🇺🇸"),
    "Milan": ("Italy", "🇮🇹"),
    "Minsk": ("Belarus", "🇧🇾"),
    "Montreal": ("Canada", "🇨🇦"),
    "Mumbai": ("India", "🇮🇳"),
    "Munich": ("Germany", "🇩🇪"),
    "Naples": ("Italy", "🇮🇹"),
    "Nice": ("France", "🇫🇷"),
    "Nizhniy Novgorod": ("Russia", "🇷🇺"),
    "Osaka": ("Japan", "🇯🇵"),
    "Palma de Mallorca": ("Spain", "🇪🇸"),
    "Pattaya": ("Thailand", "🇹🇭"),
    "Penang": ("Malaysia", "🇲🇾"),
    "Phuket": ("Thailand", "🇹🇭"),
    "Porto": ("Portugal", "🇵🇹"),
    "Rhodes": ("Greece", "🇬🇷"),
    "Rio de Janeiro": ("Brazil", "🇧🇷"),
    "Riyadh": ("Saudi Arabia", "🇸🇦"),
    "Salvador": ("Brazil", "🇧🇷"),
    "San Francisco": ("USA", "🇺🇸"),
    "Seattle": ("USA", "🇺🇸"),
    "Seoul": ("South Korea", "🇰🇷"),
    "Shanghai": ("China", "🇨🇳"),
    "Shenzhen": ("China", "🇨🇳"),
    "Singapore": ("Singapore", "🇸🇬"),
    "Stockholm": ("Sweden", "🇸🇪"),
    "Sydney": ("Australia", "🇦🇺"),
    "Taipei": ("Taiwan", "🇹🇼"),
    "Taiwan": ("Taiwan", "🇹🇼"),
    "Tbilisi": ("Georgia", "🇬🇪"),
    "Tel Aviv": ("Israel", "🇮🇱"),
    "Toronto": ("Canada", "🇨🇦"),
    "Vancouver": ("Canada", "🇨🇦"),
    "Venice": ("Italy", "🇮🇹"),
    "Vitebsk": ("Belarus", "🇧🇾"),
    "Zhuhai": ("China", "🇨🇳"),
    "Cairo": ("Egypt", "🇪🇬"),
    "Chisinau": ("Moldova", "🇲🇩"),
    "Cologne": ("Germany", "🇩🇪"),
    "Copenhagen": ("Denmark", "🇩🇰"),
    "Dallas": ("USA", "🇺🇸"),
    "Orlando": ("USA", "🇺🇸"),
}

def add_flags_to_cities(input_path, output_path):
    with open(input_path, 'r', encoding='utf-8') as f:
        cities = json.load(f)

    for city in cities:
        # If already has country and flag, skip
        if 'country' in city and 'flag' in city:
            continue
        # Try to get from city mapping
        if city['name'] in CITY_COUNTRY_FLAG:
            country, flag = CITY_COUNTRY_FLAG[city['name']]
            city['country'] = country
            city['flag'] = flag
        # Otherwise, set to unknown
        else:
            city['country'] = city.get('country', 'Unknown')
            city['flag'] = '🏳️'

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(cities, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":
    add_flags_to_cities('cities.json', 'cities_with_flags.json') 