import json

# Словарь переводов стран
country_translations = {
    'Russia': 'Россия',
    'UAE': 'ОАЭ',
    'India': 'Индия',
    'Turkey': 'Турция',
    'Netherlands': 'Нидерланды',
    'Greece': 'Греция',
    'Azerbaijan': 'Азербайджан',
    'Thailand': 'Таиланд',
    'Spain': 'Испания',
    'Georgia': 'Грузия',
    'China': 'Китай',
    'Germany': 'Германия',
    'Colombia': 'Колумбия',
    'France': 'Франция',
    'Belarus': 'Беларусь',
    'Czech Republic': 'Чехия',
    'Belgium': 'Бельгия',
    'Romania': 'Румыния',
    'Hungary': 'Венгрия',
    'Bulgaria': 'Болгария',
    'Egypt': 'Египет',
    'Ireland': 'Ирландия',
    'USA': 'США',
    'Vietnam': 'Вьетнам',
    'South Korea': 'Южная Корея',
    'Saudi Arabia': 'Саудовская Аравия',
    'Indonesia': 'Индонезия',
    'Portugal': 'Португалия',
    'UK': 'Великобритания',
    'Mexico': 'Мексика',
    'Canada': 'Канада',
    'Italy': 'Италия',
    'Brazil': 'Бразилия',
    'Japan': 'Япония',
    'Switzerland': 'Швейцария',
    'Singapore': 'Сингапур',
    'Australia': 'Австралия',
    'Moldova': 'Молдова',
    'Denmark': 'Дания',
    'Israel': 'Израиль',
    'Malaysia': 'Малайзия',
    'Armenia': 'Армения',
    'Latvia': 'Латвия',
    'Estonia': 'Эстония',
    'Uzbekistan': 'Узбекистан',
    'Kyrgyzstan': 'Кыргызстан',
    'Austria': 'Австрия',
    'Poland': 'Польша',
    'Finland': 'Финляндия',
    'Croatia': 'Хорватия',
    'Taiwan': 'Тайвань',
    'Unknown': 'Неизвестно',
    'UA': 'Украина',
    'Hong Kong': 'Гонконг',
    'South Africa': 'ЮАР',
    'Sri Lanka': 'Шри-Ланка',
    'Norway': 'Норвегия',
    'Sweden': 'Швеция',
    'Lithuania': 'Литва',
    'Serbia': 'Сербия',
    'Slovakia': 'Словакия',
    'Slovenia': 'Словения',
    'Montenegro': 'Черногория',
    'Gibraltar': 'Гибралтар',
    'Philippines': 'Филиппины',
    'Jordan': 'Иордания',
    'Morocco': 'Марокко',
    'Cyprus': 'Кипр',
    'Turkeye': 'Турция',
}

# Словарь переводов городов (дополняется по необходимости)
city_translations = {
    'Cheboksary': 'Чебоксары',
    'Chelyabinsk': 'Челябинск',
    'Paris': 'Париж',
    'Singapore': 'Сингапур',
    'Tokyo': 'Токио',
    'London': 'Лондон',
    'New York': 'Нью-Йорк',
    'Los Angeles': 'Лос-Анджелес',
    'San Francisco': 'Сан-Франциско',
    'Toronto': 'Торонто',
    'Munich': 'Мюнхен',
    'Berlin': 'Берлин',
    'Rome': 'Рим',
    'Venice': 'Венеция',
    'Milan': 'Милан',
    'Florence': 'Флоренция',
    'Naples': 'Неаполь',
    'Nice': 'Ницца',
    'Madrid': 'Мадрид',
    'Barcelona': 'Барселона',
    'Lisbon': 'Лиссабон',
    'Prague': 'Прага',
    'Vienna': 'Вена',
    'Budapest': 'Будапешт',
    'Warsaw': 'Варшава',
    'Brussels': 'Брюссель',
    'Amsterdam': 'Амстердам',
    'Copenhagen': 'Копенгаген',
    'Stockholm': 'Стокгольм',
    'Oslo': 'Осло',
    'Helsinki': 'Хельсинки',
    'Zurich': 'Цюрих',
    'Geneva': 'Женева',
    'Bern': 'Берн',
    'Basel': 'Базель',
    'Dublin': 'Дублин',
    'Edinburgh': 'Эдинбург',
    'Glasgow': 'Глазго',
    'Manchester': 'Манчестер',
    'Liverpool': 'Ливерпуль',
    'Birmingham': 'Бирмингем',
    'Sydney': 'Сидней',
    'Melbourne': 'Мельбурн',
    'Brisbane': 'Брисбен',
    'Perth': 'Перт',
    'Auckland': 'Окленд',
    'Wellington': 'Веллингтон',
    'Christchurch': 'Крайстчерч',
    'Shanghai': 'Шанхай',
    'Beijing': 'Пекин',
    'Hong Kong': 'Гонконг',
    'Macau': 'Макао',
    'Bangkok': 'Бангкок',
    'Phuket': 'Пхукет',
    'Pattaya': 'Паттайя',
    'Kuala Lumpur': 'Куала-Лумпур',
    'Penang': 'Пинанг',
    'Jakarta': 'Джакарта',
    'Bali': 'Бали',
    'Denpasar': 'Денпасар',
    'Ubud': 'Убуд',
    'Singapore': 'Сингапур',
    'Seoul': 'Сеул',
    'Busan': 'Пусан',
    'Jeju': 'Чеджу',
    'Taipei': 'Тайбэй',
    'Kaohsiung': 'Гаосюн',
    'Hanoi': 'Ханой',
    'Ho Chi Minh City': 'Хошимин',
    'Da Nang': 'Дананг',
    'Nha Trang': 'Нячанг',
    'Hue': 'Хюэ',
    'Siem Reap': 'Сиемреап',
    'Phnom Penh': 'Пномпень',
    'Vientiane': 'Вьентьян',
    'Luang Prabang': 'Луангпхабанг',
    'Yangon': 'Янгон',
    'Mandalay': 'Мандалай',
    'Bagan': 'Баган',
    'Moscow': 'Москва',
    'Saint Petersburg': 'Санкт-Петербург',
    'Sochi': 'Сочи',
    'Kazan': 'Казань',
    'Vladivostok': 'Владивосток',
    'Novosibirsk': 'Новосибирск',
    'Yekaterinburg': 'Екатеринбург',
    'Nizhny Novgorod': 'Нижний Новгород',
    'Samara': 'Самара',
    'Omsk': 'Омск',
    'Rostov-on-Don': 'Ростов-на-Дону',
    'Ufa': 'Уфа',
    'Krasnoyarsk': 'Красноярск',
    'Perm': 'Пермь',
    'Volgograd': 'Волгоград',
    'Voronezh': 'Воронеж',
    'Krasnodar': 'Краснодар',
    'Saratov': 'Саратов',
    'Tyumen': 'Тюмень',
    'Tolyatti': 'Тольятти',
    'Izhevsk': 'Ижевск',
    'Barnaul': 'Барнаул',
    'Ulyanovsk': 'Ульяновск',
    'Irkutsk': 'Иркутск',
    'Khabarovsk': 'Хабаровск',
    'Yaroslavl': 'Ярославль',
    'Vladikavkaz': 'Владикавказ',
    'Kemerovo': 'Кемерово',
    'Tomsk': 'Томск',
    'Orenburg': 'Оренбург',
    'Novokuznetsk': 'Новокузнецк',
    'Ryazan': 'Рязань',
    'Astrakhan': 'Астрахань',
    'Penza': 'Пенза',
    'Lipetsk': 'Липецк',
    'Kirov': 'Киров',
    'Cheboksary': 'Чебоксары',
    'Bryansk': 'Брянск',
    'Smolensk': 'Смоленск',
    'Kaluga': 'Калуга',
    'Kostroma': 'Кострома',
    'Vologda': 'Вологда',
    'Murmansk': 'Мурманск',
    'Arkhangelsk': 'Архангельск',
    'Syktyvkar': 'Сыктывкар',
    'Petrozavodsk': 'Петрозаводск',
    'Chita': 'Чита',
    'Yakutsk': 'Якутск',
    'Magadan': 'Магадан',
    'Norilsk': 'Норильск',
    'Krasnogorsk': 'Красногорск',
    'Khimki': 'Химки',
    'Podolsk': 'Подольск',
    'Balashikha': 'Балашиха',
    'Korolev': 'Королёв',
    'Mytishchi': 'Мытищи',
    'Lyubertsy': 'Люберцы',
    'Kursk': 'Курск',
    'Tula': 'Тула',
    'Tver': 'Тверь',
    'Belgorod': 'Белгород',
    'Vladimir': 'Владимир',
    'Sevastopol': 'Севастополь',
    'Simferopol': 'Симферополь',
    'Yalta': 'Ялта',
    'Kerch': 'Керчь',
    'Feodosia': 'Феодосия',
    'Evpatoria': 'Евпатория',
    'Alushta': 'Алушта',
    'Saki': 'Саки',
    'Bakhchisaray': 'Бахчисарай',
    'Sudak': 'Судак',
    'Dzhankoy': 'Джанкой',
    'Armyansk': 'Армянск',
    'Krasnoperekopsk': 'Красноперекопск',
    'Zheleznogorsk': 'Железногорск',
    'Zhukovsky': 'Жуковский',
    'Zelenograd': 'Зеленоград',
    'Zaraysk': 'Зарайск',
    'Zvenigorod': 'Звенигород',
    'Zyuzino': 'Зюзино',
    'Zamoskvorechye': 'Замоскворечье',
    'Zamoskvorechye District': 'Замоскворечье',
    'Zamoskvorechye Rayon': 'Замоскворечье',
    'Zamoskvorechye raion': 'Замоскворечье',
    'Zamoskvorechye region': 'Замоскворечье',
    'Zamoskvorechye area': 'Замоскворечье',
    'Zamoskvorechye Moscow': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia': 'Замоскворечье',
    'Zamoskvorechye Moscow oblast': 'Замоскворечье',
    'Zamoskvorechye Moscow region': 'Замоскворечье',
    'Zamoskvorechye Moscow area': 'Замоскворечье',
    'Zamoskvorechye Moscow raion': 'Замоскворечье',
    'Zamoskvorechye Moscow district': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia oblast': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia region': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia area': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia raion': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia district': 'Замоскворечье',
    'Zamoskvorechye Moscow Russia oblast region area raion district': 'Замоскворечье',
}

with open('cities.json', 'r', encoding='utf-8') as f:
    cities = json.load(f)

updated = 0
for city in cities:
    # Перевод страны
    if city['country'] in country_translations:
        city['country'] = country_translations[city['country']]
        updated += 1
    # Перевод города
    if city['name'] in city_translations:
        city['name'] = city_translations[city['name']]
        updated += 1

with open('cities.json', 'w', encoding='utf-8') as f:
    json.dump(cities, f, ensure_ascii=False, indent=2)

print(f'Обновлено {updated} записей. Все возможные города и страны переведены на русский.') 